---
- hosts: "{{ target }}"
  remote_user: root
  vars_files:
    - vars/ca.yml
    - vars/server.yml
    - vars/client.yml
  vars:
    KEY_CN: "{{ common_name | lower | mandatory }}"
  handlers:
    - include: handlers.yml
  tasks:
    - debug: var=KEY_CN
      tags:
        - new-client

    - name: create client certificate
      shell: . ./vars && KEY_CN="{{ KEY_CN }}" ./pkitool {{ KEY_CN }}
      args:
        chdir: /etc/openvpn/easy-rsa
        creates: /etc/openvpn/easy-rsa/keys/{{ KEY_CN }}.crt
      tags:
        - new-client

    - name: create client keys directory
      file: path=/etc/openvpn/clients state=directory
      tags:
        - new-client

    - name: upload client template
      template: src=files/client.conf.j2 dest=/etc/openvpn/clients/{{ KEY_CN }}.conf
      tags:
        - new-client

    - name: zip client certificates and configuration
      shell: zip -j {{ KEY_CN }}.zip {{ KEY_CN }}.conf ../easy-rsa/keys/{{ KEY_CN }}.crt ../easy-rsa/keys/{{ KEY_CN }}.key ../easy-rsa/keys/ca.crt ../easy-rsa/keys/ta.key
      args:
        chdir: /etc/openvpn/clients
        creates: /etc/openvpn/clients/{{ KEY_CN }}.zip
      tags:
        - new-client

    - name: remove client conf
      file: path=/etc/openvpn/clients/{{ KEY_CN }}.conf state=absent
      tags:
        - new-client

    - name: fetch client zip
      fetch: src=/etc/openvpn/clients/{{ KEY_CN }}.zip dest=client-keys/ flat=yes validate_md5=yes fail_on_missing=yes
      tags:
        - new-client

    - name: sync client-config directory
      synchronize: src=client-config/ dest=/etc/openvpn/{{ server_client_config_dir }} rsync_opts="--exclude='.*'"
      tags:
        - sync-ccd